### ISSUE TITLE
1-dimensional array requirement for input of PragmaSetDensityMatrix, PragmaGeneralNoise

### ISSUE THREAD

**Issue by kbarkhqs** [HQSquantumsimulations/qoqo#37]
Currently the inputs for PragmaSetDensityMatrix (density_matrix) and PragmaGeneralNoise (operators) need to be flattened in python using np.flatten before being passed as inputs to the Pragmas. This should be fixed so that these two pragmas take 2d matrices as inputs, without needing to flatten.

**Comment by nfwvogt** [comment]
We should use something along those lines:

```rust
use numpy::PyReadonlyArray2;

fn new(density_matrix: PyReadonlyArray2<Complex64>) {
let density_matrix_for_initialisation = density_matrix.as_array().to_owned()
}
```

**Comment by mwalthqs** [comment]
implemented and merged
